version: 2.1
executors:
    bazel:
        docker:
            - image: cimg/base:2022.08

jobs:
    test:
        executor: bazel
        steps:
            - checkout
            - run:
                  name: Install Bazel
                  command: |
                      sudo apt install apt-transport-https curl gnupg
                      curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
                      sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
                      echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
                      sudo apt install bazel
            - run:
                  name: Setup Keys
                  command: |
                      echo "build --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY}" > .bazelrc.local
            - run:
                  name: bazel test ...
                  command: bazel test ...
workflows:
    test:
        jobs:
            - test
